version: '2'
services:

  web:
    build: ./web
    expose:
      - 8082
    ports:
      - "9000:8082"

  backend:
    build: .
    expose:
      - 8080
    ports:
      - "8080:8080"

  db:
    image: postgres
    volumes:
      - ~/work/data/nufito_db/db_data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "1234:5432"
