weba:
  image: piotrprzybylak/nufito-prod
  expose:
    - 8080
  ports:
    - "8080:8080"
  links:
    - db

db:
  image: postgres
  volumes:
    - ./db_data:/var/lib/postgresql/data
  expose:
    - 5432
  ports:
    - "1234:5432"
